package com.dogadopt.dog_adopt.domain.enums;

import lombok.Getter;

@Getter
public enum DogBreed {
    OTHER("Other", "Egyéb"),
    MIXED_BREED("Mixed Breed", "Keverék"),
    AKITA("Akita", "Akita"),
    ALASKAN_MALAMUTE("Alaskan Malamute", "Alaszkai Malamute"),
    BASENJI("Basenji", "Basenji"),
    BEAGLE("Beagle", "Beagle"),
    BELGIAN_MALINOIS("Belgian Malinois", "Belgian Malinois"),
    BICHON_FRISE("Bichon Frise", "Bichon Frise"),
    BORDER_COLLIE("Border Collie", "Border Collie"),
    BORDER_TERRIER("Border Terrier", "Border Terrier"),
    BOXER("Boxer", "Boxer"),
    BRITTANY("Brittany", "Brittany"),
    BULL_TERRIER("Bull Terrier", "Bull Terrier"),
    BULLDOG("Bulldog", "Bulldog"),
    CAJUN_MASTIFF("Cajun Mastiff", "Cajun Mastiff"),
    CAVALIER_KING_CHARLES_SPANIEL("Cavalier King Charles Spaniel", "Cavalier King Charles Spaniel"),
    CHIHUAHUA("Chihuahua", "Chihuahua"),
    CHOW_CHOW("Chow Chow", "Chow Chow"),
    CORGHI("Corgi", "Corgi"),
    DACHSHUND("Dachshund", "Dachshund"),
    DALMATIAN("Dalmatian", "Dalmatiai"),
    DOGO_ARGENTINO("Dogo Argentino", "Argentin Dogo"),
    DOGUE_DE_BORDEAUX("Dogue de Bordeaux", "Bordeaux-i Dogue"),
    ENGLISH_BULLDOG("English Bulldog", "Angol Bulldog"),
    ENGLISH_SETTER("English Setter", "Angol Szetter"),
    FRENCH_BULLDOG("French Bulldog", "Francia Bulldog"),
    GERMAN_PINSCHER("German Pinscher", "Német Pinscher"),
    GERMAN_SHEPHERD("German Shepherd", "Német Juhászkutya"),
    GOLDEN_RETRIEVER("Golden Retriever", "Golden Retriever"),
    GREAT_DANE("Great Dane", "Nagy Dáni"),
    GREYHOUND("Greyhound", "Agár"),
    HUSKY("Husky", "Husky"),
    IRISH_SETTER("Irish Setter", "Ír Szetter"),
    JACK_RUSSELL_TERRIER("Jack Russell Terrier", "Jack Russell Terrier"),
    LABRADOR_RETRIEVER("Labrador Retriever", "Labrador Retriever"),
    MALTESE("Maltese", "Maltai"),
    NEWFOUNDLAND("Newfoundland", "Újfundlandi"),
    PAPILLON("Papillon", "Papillon"),
    PEKINGESE("Pekingese", "Pekingese"),
    PIT_BULL("Pit Bull", "Pit Bull"),
    POINTER("Pointer", "Pointer"),
    POODLE("Poodle", "Poodle"),
    PUG("Pug", "Mopsz"),
    RETRIEVER("Retriever", "Retriver"),
    ROTTWEILER("Rottweiler", "Rottweiler"),
    SHEEPDOG("Sheepdog", "Juhászkutya"),
    SHIH_TZU("Shih Tzu", "Shih Tzu"),
    SIBERIAN_HUSKY("Siberian Husky", "Szibériai Husky"),
    SILKY_TERRIER("Silky Terrier", "Selyem Terrier"),
    TERRIER("Terrier", "Terrier"),
    VIZSLA("Vizsla", "Vizsla"),
    WEIMARANER("Weimaraner", "Weimari"),
    WHIPPET("Whippet", "Whippet"),
    YORKSHIRE_TERRIER("Yorkshire Terrier", "Yorkshire Terrier"),
    AFGHAN_HOUND("Afghan Hound", "Afgan Agár"),
    AMERICAN_BULLDOG("American Bulldog", "Amerikai Bulldog"),
    AMERICAN_ESKIMO_DOG("American Eskimo Dog", "Amerikai Eszkimó Kutya"),
    AUSTRALIAN_CATTLE_DOG("Australian Cattle Dog", "Ausztrál Szarvasmarha Kutya"),
    AUSTRALIAN_SHEPHERD("Australian Shepherd", "Ausztrál Juhászkutya"),
    BASSET_HOUND("Basset Hound", "Basset Hound"),
    BICHON_AUX_LANGES("Bichon aux Langes", "Bichon aux Langes"),
    BORZOI("Borzois", "Borzois"),
    BOSTON_TERRIER("Boston Terrier", "Boston Terrier"),
    BRIARD("Briard", "Briard"),
    CARDIGAN_WELSH_CORGI("Cardigan Welsh Corgi", "Cardigan Welsh Corgi"),
    CATAHOULA_LEOPARD_DOG("Catahoula Leopard Dog", "Catahoula Leopárd Kutya"),
    CHESAPEAKE_BAY_RETRIEVER("Chesapeake Bay Retriever", "Chesapeake-öböl Retriever"),
    COTON_DE_TULEAR("Coton de Tulear", "Coton de Tulear"),
    DANDIE_DINMONT_TERRIER("Dandie Dinmont Terrier", "Dandie Dinmont Terrier"),
    ENGLISH_COCKER_SPANIEL("English Cocker Spaniel", "Angol Cocker Spaniel"),
    FILA_BRASILEIRO("Fila Brasileiro", "Brasília-i Fila"),
    GERMAN_SHORTHAIRED_POINTER("German Shorthaired Pointer", "Német Rövidszőrű Pointer"),
    GOLDEN_DOODLE("Golden Doodle", "Golden Doodle"),
    HAVANESE("Havanese", "Havanese"),
    IRISH_WOLFHOUND("Irish Wolfhound", "Ír Farkaskutya"),
    KUVASZ("Kuvaz", "Kuvaz"),
    LAGOTTO_ROMAGNOLO("Lagotto Romagnolo", "Lagotto Romagnolo"),
    MASTIFF("Mastiff", "Mastiff"),
    MINIATURE_PINSCHER("Miniature Pinscher", "Törpe Pinscher"),
    OLD_ENGLISH_SHEEPDOG("Old English Sheepdog", "Régi Angol Juhászkutya"),
    RUSSIAN_TERRIER("Russian Terrier", "Orosz Terrier"),
    SCOTTISH_DEERHOUND("Scottish Deerhound", "Skót Szarvas Kutya"),
    SHETLAND_SHEEPDOG("Shetland Sheepdog", "Shetlandi Juhászkutya"),
    TIBETAN_MASTIFF("Tibetan Mastiff", "Tibeti Masztiff"),
    TIBETAN_TERRIER("Tibetan Terrier", "Tibeti Terrier");

    private final String englishBreedName;
    private final String hungarianBreedName;

    DogBreed(String englishBreedName, String hungarianBreedName) {
        this.englishBreedName = englishBreedName;
        this.hungarianBreedName = hungarianBreedName;
    }
}
