server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dog-adopt?createDatabaseIfNotExist=true&serverTimezone=Europe/Budapest&characterEncoding=utf8
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  mail:
    host: smtp.mail.yahoo.com
    port: 587
    username: sandorciv@yahoo.com
    password: ictk mwbk cfdy vjbd
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    com.progmasters: debug
    org.springframework.web: info
    org.hibernate: error
    security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

paypal:
  client-id: AbP6iKvblPkL90V8CYNofKKDdVrAYQT3vEMPULqcK2eCJbtvawawjMw-yUy0hN7b8bv7D1VcDH22-DpK
  client-secret: EP_0eLDvGw8c6Otv3hEuPb_ubbpE7af3oMbvXmpEIiVfBks1Qzqx1i4r5k658p6N8bfQGDbW1E8g2Wrs
  mode: sandbox # Use #sandbox' for testing and 'live' for Production