server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dog-adopt?createDatabaseIfNotExist=true&serverTimezone=Europe/Budapest&characterEncoding=utf8
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  mail:
    host: smtp.mail.yahoo.com
    port: 587
    username: sandorciv@yahoo.com
    password: ictk mwbk cfdy vjbd
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
