package com.dogadopt.dog_adopt.domain.enums.address;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Country {
    AFGHANISTAN("Afghanistan", "Afganisztán", "AF", "+93"),
    ALBANIA("Albania", "Albánia", "AL", "+355"),
    ALGERIA("Algeria", "Algéria", "DZ", "+213"),
    ANDORRA("Andorra", "Andorra", "AD", "+376"),
    ANGOLA("Angola", "Angola", "AO", "+244"),
    ANTIGUA_AND_BARBUDA("Antigua and Barbuda", "Antigua és Barbuda", "AG", "+1-268"),
    ARGENTINA("Argentina", "Argentína", "AR", "+54"),
    ARMENIA("Armenia", "Örményország", "AM", "+374"),
    AUSTRALIA("Australia", "Ausztrália", "AU", "+61"),
    AUSTRIA("Austria", "Ausztria", "AT", "+43"),
    AZERBAIJAN("Azerbaijan", "Azerbajdzsán", "AZ", "+994"),
    BAHAMAS("Bahamas", "Bahama-szigetek", "BS", "+1-242"),
    BAHRAIN("Bahrain", "Bahrein", "BH", "+973"),
    BANGLADESH("Bangladesh", "Banglades", "BD", "+880"),
    BARBADOS("Barbados", "Barbados", "BB", "+1-246"),
    BELARUS("Belarus", "Fehéroroszország", "BY", "+375"),
    BELGIUM("Belgium", "Belgium", "BE", "+32"),
    BELIZE("Belize", "Beliz", "BZ", "+501"),
    BENIN("Benin", "Benin", "BJ", "+229"),
    BHUTAN("Bhutan", "Bhután", "BT", "+975"),
    BOLIVIA("Bolivia", "Bolívia", "BO", "+591"),
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina", "Bosznia és Hercegovina", "BA", "+387"),
    BOTSWANA("Botswana", "Botswana", "BW", "+267"),
    BRAZIL("Brazil", "Brazília", "BR", "+55"),
    BRUNEI("Brunei", "Brunei", "BN", "+673"),
    BULGARIA("Bulgaria", "Bulgária", "BG", "+359"),
    BURKINA_FASO("Burkina Faso", "Burkina Faso", "BF", "+226"),
    BURUNDI("Burundi", "Burundi", "BI", "+257"),
    CABO_VERDE("Cabo Verde", "Zöld-foki-szigetek", "CV", "+238"),
    CAMBODIA("Cambodia", "Kambodzsa", "KH", "+855"),
    CAMEROON("Cameroon", "Kamerun", "CM", "+237"),
    CANADA("Canada", "Kanada", "CA", "+1"),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic", "Közép-afrikai Köztársaság", "CF", "+236"),
    CHAD("Chad", "Csád", "TD", "+235"),
    CHILE("Chile", "Chile", "CL", "+56"),
    CHINA("China", "Kína", "CN", "+86"),
    COLOMBIA("Colombia", "Kolumbia", "CO", "+57"),
    COMOROS("Comoros", "Komorok", "KM", "+269"),
    CONGO_DEMOCRATIC_REPUBLIC_OF_THE("Congo, Democratic Republic of the", "Kongói Demokratikus Köztársaság", "CD", "+243"),
    CONGO_REPUBLIC_OF_THE("Congo, Republic of the", "Kongói Köztársaság", "CG", "+242"),
    COSTA_RICA("Costa Rica", "Costa Rica", "CR", "+506"),
    COTE_D_IVOIRE("Côte d'Ivoire", "Elefántcsontpart", "CI", "+225"),
    CROATIA("Croatia", "Horvátország", "HR", "+385"),
    CUBA("Cuba", "Kubai", "CU", "+53"),
    CYPRUS("Cyprus", "Ciprus", "CY", "+357"),
    CZECHIA("Czechia", "Csehország", "CZ", "+420"),
    DENMARK("Denmark", "Dánia", "DK", "+45"),
    DJIBOUTI("Djibouti", "Dzsibuti", "DJ", "+253"),
    DOMINICA("Dominica", "Dominika", "DM", "+1-767"),
    DOMINICAN_REPUBLIC("Dominican Republic", "Dominikai Köztársaság", "DO", "+1-809"),
    ECUADOR("Ecuador", "Ecuador", "EC", "+593"),
    EGYPT("Egypt", "Egyiptom", "EG", "+20"),
    EL_SALVADOR("El Salvador", "Salvador", "SV", "+503"),
    EQUATORIAL_GUINEA("Equatorial Guinea", "Egyenlítői-Guinea", "GQ", "+240"),
    ERITREA("Eritrea", "Eritrea", "ER", "+291"),
    ESTONIA("Estonia", "Észtország", "EE", "+372"),
    ESWATINI("Eswatini", "Eswatini", "SZ", "+268"),
    ETHIOPIA("Ethiopia", "Etiópia", "ET", "+251"),
    FIJI("Fiji", "Fidzsi", "FJ", "+679"),
    FINLAND("Finland", "Finnország", "FI", "+358"),
    FRANCE("France", "Franciaország", "FR", "+33"),
    GABON("Gabon", "Gabon", "GA", "+241"),
    GAMBIA("Gambia", "Gambia", "GM", "+220"),
    GEORGIA("Georgia", "Grúzia", "GE", "+995"),
    GERMANY("Germany", "Németország", "DE", "+49"),
    GHANA("Ghana", "Ghána", "GH", "+233"),
    GREECE("Greece", "Görögország", "GR", "+30"),
    GRENADA("Grenada", "Grenada", "GD", "+1-473"),
    GUATEMALA("Guatemala", "Guatemala", "GT", "+502"),
    GUINEA("Guinea", "Guinea", "GN", "+224"),
    GUINEA_BISSAU("Guinea-Bissau", "Bissau-Guinea", "GW", "+245"),
    GUYANA("Guyana", "Guyana", "GY", "+592"),
    HAITI("Haiti", "Haiti", "HT", "+509"),
    HONDURAS("Honduras", "Honduras", "HN", "+504"),
    HUNGARY("Hungary", "Magyarország", "HU", "+36"),
    ICELAND("Iceland", "Izland", "IS", "+354"),
    INDIA("India", "India", "IN", "+91"),
    INDONESIA("Indonesia", "Indonézia", "ID", "+62"),
    IRAN("Iran", "Irán", "IR", "+98"),
    IRAQ("Iraq", "Irak", "IQ", "+964"),
    IRELAND("Ireland", "Írország", "IE", "+353"),
    ISRAEL("Israel", "Izrael", "IL", "+972"),
    ITALY("Italy", "Olaszország", "IT", "+39"),
    JAMAICA("Jamaica", "Jamaika", "JM", "+1-876"),
    JAPAN("Japan", "Japán", "JP", "+81"),
    JORDAN("Jordan", "Jordánia", "JO", "+962"),
    KAZAKHSTAN("Kazakhstan", "Kazahsztán", "KZ", "+7"),
    KENYA("Kenya", "Kenya", "KE", "+254"),
    KIRIBATI("Kiribati", "Kiribati", "KI", "+686"),
    KOREA_NORTH("Korea, North", "Észak-Korea", "KP", "+850"),
    KOREA_SOUTH("Korea, South", "Dél-Korea", "KR", "+82"),
    KOSOVO("Kosovo", "Koszovó", "XK", "+383"),
    KUWAIT("Kuwait", "Kuvait", "KW", "+965"),
    KYRGYZSTAN("Kyrgyzstan", "Kirgizisztán", "KG", "+996"),
    LAOS("Laos", "Laos", "LA", "+856"),
    LATVIA("Latvia", "Lettország", "LV", "+371"),
    LEBANON("Lebanon", "Libanon", "LB", "+961"),
    LESOTHO("Lesotho", "Lesotho", "LS", "+266"),
    LIBERIA("Liberia", "Libéria", "LR", "+231"),
    LIBYA("Libya", "Líbia", "LY", "+218"),
    LIECHTENSTEIN("Liechtenstein", "Liechtenstein", "LI", "+423"),
    LITHUANIA("Lithuania", "Litvánia", "LT", "+370"),
    LUXEMBOURG("Luxembourg", "Luxemburg", "LU", "+352"),
    MADAGASCAR("Madagascar", "Madagaszkár", "MG", "+261"),
    MALAWI("Malawi", "Malawi", "MW", "+265"),
    MALAYSIA("Malaysia", "Malajzia", "MY", "+60"),
    MALDIVES("Maldives", "Maldív-szigetek", "MV", "+960"),
    MALI("Mali", "Mali", "ML", "+223"),
    MALTA("Malta", "Málta", "MT", "+356"),
    MAROCCO("Morocco", "Marokkó", "MA", "+212"),
    MAURITANIA("Mauritania", "Mauritánia", "MR", "+222"),
    MAURITIUS("Mauritius", "Mauríciusz", "MU", "+230"),
    MEXICO("Mexico", "Mexikó", "MX", "+52"),
    MICRONESIA("Micronesia", "Mikronézia", "FM", "+691"),
    MOLDOVA("Moldova", "Moldova", "MD", "+373"),
    MONACO("Monaco", "Monaco", "MC", "+377"),
    MONGOLIA("Mongolia", "Mongólia", "MN", "+976"),
    MONTENEGRO("Montenegro", "Montenegró", "ME", "+382"),
    MOROCCO("Morocco", "Marokkó", "MA", "+212"),
    MOZAMBIQUE("Mozambique", "Mozambik", "MZ", "+258"),
    MYANMAR("Myanmar", "Mianmar", "MM", "+95"),
    NAMIBIA("Namibia", "Namíbia", "NA", "+264"),
    NAURU("Nauru", "Nauru", "NR", "+674"),
    NEPAL("Nepal", "Nepál", "NP", "+977"),
    NETHERLANDS("Netherlands", "Hollandia", "NL", "+31"),
    NEW_ZEALAND("New Zealand", "Új-Zéland", "NZ", "+64"),
    NICARAGUA("Nicaragua", "Nicaragua", "NI", "+505"),
    NIGER("Niger", "Niger", "NE", "+227"),
    NIGERIA("Nigeria", "Nigéria", "NG", "+234"),
    NORTH_MACEDONIA("North Macedonia", "Észak-Macedónia", "MK", "+389"),
    NORWAY("Norway", "Norvégia", "NO", "+47"),
    OMAN("Oman", "Omán", "OM", "+968"),
    PAKISTAN("Pakistan", "Pakisztán", "PK", "+92"),
    PANAMA("Panama", "Panama", "PA", "+507"),
    PAPUA_NEW_GUINEA("Papua New Guinea", "Pápua Új-Guinea", "PG", "+675"),
    PARAGUAY("Paraguay", "Paraguay", "PY", "+595"),
    PERU("Peru", "Peru", "PE", "+51"),
    PHILIPPINES("Philippines", "Fülöp-szigetek", "PH", "+63"),
    POLAND("Poland", "Lengyelország", "PL", "+48"),
    PORTUGAL("Portugal", "Portugália", "PT", "+351"),
    QATAR("Qatar", "Katar", "QA", "+974"),
    ROMANIA("Romania", "Románia", "RO", "+40"),
    RUSSIA("Russia", "Oroszország", "RU", "+7"),
    RWANDA("Rwanda", "Ruanda", "RW", "+250"),
    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis", "Saint Kitts és Nevis", "KN", "+1-869"),
    SAINT_LUCIA("Saint Lucia", "Saint Lucia", "LC", "+1-758"),
    SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines", "Saint Vincent és a Grenadine-szigetek", "VC", "+1-784"),
    SAMOA("Samoa", "Samoa", "WS", "+685"),
    SAN_MARINO("San Marino", "San Marino", "SM", "+378"),
    SAUDI_ARABIA("Saudi Arabia", "Szaúd-Arábia", "SA", "+966"),
    SENEGAL("Senegal", "Szenegál", "SN", "+221"),
    SERBIA("Serbia", "Szerbia", "RS", "+381"),
    SEYCHELLES("Seychelles", "Seychelle-szigetek", "SC", "+248"),
    SIERRA_LEONE("Sierra Leone", "Sierra Leone", "SL", "+232"),
    SINGAPORE("Singapore", "Szingapúr", "SG", "+65"),
    SLOVAKIA("Slovakia", "Szlovákia", "SK", "+421"),
    SLOVENIA("Slovenia", "Szlovénia", "SI", "+386"),
    SOLOMON_ISLANDS("Solomon Islands", "Salamon-szigetek", "SB", "+677"),
    SOMALIA("Somalia", "Somália", "SO", "+252"),
    SOUTH_AFRICA("South Africa", "Dél-Afrika", "ZA", "+27"),
    SOUTH_SUDAN("South Sudan", "Dél-Szudán", "SS", "+211"),
    SPAIN("Spain", "Spanyolország", "ES", "+34"),
    SRI_LANKA("Sri Lanka", "Srí Lanka", "LK", "+94"),
    SUDAN("Sudan", "Szudán", "SD", "+249"),
    SURINAME("Suriname", "Suriname", "SR", "+597"),
    SWEDEN("Sweden", "Svédország", "SE", "+46"),
    SWITZERLAND("Switzerland", "Svájc", "CH", "+41"),
    SYRIA("Syria", "Szíria", "SY", "+963"),
    TAIWAN("Taiwan", "Taiwan", "TW", "+886"),
    TAJIKISTAN("Tajikistan", "Tádzsikisztán", "TJ", "+992"),
    TANZANIA("Tanzania", "Tanzánia", "TZ", "+255"),
    THAILAND("Thailand", "Thaiföld", "TH", "+66"),
    TOGO("Togo", "Togo", "TG", "+228"),
    TONGA("Tonga", "Tonga", "TO", "+676"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago", "Trinidad és Tobago", "TT", "+1-868"),
    TUNISIA("Tunisia", "Tunézia", "TN", "+216"),
    TURKMENISTAN("Turkmenistan", "Türkménistan", "TM", "+993"),
    TURKEY("Turkey", "Törökország", "TR", "+90"),
    UGANDA("Uganda", "Uganda", "UG", "+256"),
    UKRAINE("Ukraine", "Ukrajna", "UA", "+380"),
    UNITED_ARAB_EMIRATES("United Arab Emirates", "Egyesült Arab Emírségek", "AE", "+971"),
    UNITED_KINGDOM("United Kingdom", "Egyesült Királyság", "GB", "+44"),
    UNITED_STATES("United States", "Egyesült Államok", "US", "+1"),
    URUGUAY("Uruguay", "Uruguay", "UY", "+598"),
    UZBEKISTAN("Uzbekistan", "Üzbegisztán", "UZ", "+998"),
    VANUATU("Vanuatu", "Vanuatu", "VU", "+678"),
    VENEZUELA("Venezuela", "Venezuela", "VE", "+58"),
    VIETNAM("Vietnam", "Vietnam", "VN", "+84"),
    YEMEN("Yemen", "Jemen", "YE", "+967"),
    ZAMBIA("Zambia", "Zambia", "ZM", "+260"),
    ZIMBABWE("Zimbabwe", "Zimbabwé", "ZW", "+263");

    private final String name;
    private final String hungarianName;
    private final String countryCode;
    private final String telephoneCountryCode;

    public String getPreferredName(boolean useHungarianName) {
        return useHungarianName ? hungarianName : name;
    }
}