package com.dogadopt.dog_adopt.domain.enums.shelter;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Country {
    AFGHANISTAN("Afghanistan", "Afganisztán", "AF"),
    ALBANIA("Albania", "Albánia", "AL"),
    ALGERIA("Algeria", "Algéria", "DZ"),
    ANDORRA("Andorra", "Andorra", "AD"),
    ANGOLA("Angola", "Angola", "AO"),
    ANTIGUA_AND_BARBUDA("Antigua and Barbuda", "Antigua és Barbuda", "AG"),
    ARGENTINA("Argentina", "Argentína", "AR"),
    ARMENIA("Armenia", "Örményország", "AM"),
    AUSTRALIA("Australia", "Ausztrália", "AU"),
    AUSTRIA("Austria", "Ausztria", "AT"),
    AZERBAIJAN("Azerbaijan", "Azerbajdzsán", "AZ"),
    BAHAMAS("Bahamas", "Bahama-szigetek", "BS"),
    BAHRAIN("Bahrain", "Bahrein", "BH"),
    BANGLADESH("Bangladesh", "Banglades", "BD"),
    BARBADOS("Barbados", "Barbados", "BB"),
    BELARUS("Belarus", "Fehéroroszország", "BY"),
    BELGIUM("Belgium", "Belgium", "BE"),
    BELIZE("Belize", "Beliz", "BZ"),
    BENIN("Benin", "Benin", "BJ"),
    BHUTAN("Bhutan", "Bhután", "BT"),
    BOLIVIA("Bolivia", "Bolívia", "BO"),
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina", "Bosznia és Hercegovina", "BA"),
    BOTSWANA("Botswana", "Botswana", "BW"),
    BRAZIL("Brazil", "Brazília", "BR"),
    BRUNEI("Brunei", "Brunei", "BN"),
    BULGARIA("Bulgaria", "Bulgária", "BG"),
    BURKINA_FASO("Burkina Faso", "Burkina Faso", "BF"),
    BURUNDI("Burundi", "Burundi", "BI"),
    CABO_VERDE("Cabo Verde", "Zöld-foki-szigetek", "CV"),
    CAMBODIA("Cambodia", "Kambodzsa", "KH"),
    CAMEROON("Cameroon", "Kamerun", "CM"),
    CANADA("Canada", "Kanada", "CA"),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic", "Közép-afrikai Köztársaság", "CF"),
    CHAD("Chad", "Csád", "TD"),
    CHILE("Chile", "Chile", "CL"),
    CHINA("China", "Kína", "CN"),
    COLOMBIA("Colombia", "Kolumbia", "CO"),
    COMOROS("Comoros", "Komorok", "KM"),
    CONGO_DEMOCRATIC_REPUBLIC_OF_THE("Congo, Democratic Republic of the", "Kongói Demokratikus Köztársaság", "CD"),
    CONGO_REPUBLIC_OF_THE("Congo, Republic of the", "Kongói Köztársaság", "CG"),
    COSTA_RICA("Costa Rica", "Costa Rica", "CR"),
    COTE_D_IVOIRE("Côte d'Ivoire", "Elefántcsontpart", "CI"),
    CROATIA("Croatia", "Horvátország", "HR"),
    CUBA("Cuba", "Kubai", "CU"),
    CYPRUS("Cyprus", "Ciprus", "CY"),
    CZECHIA("Czechia", "Csehország", "CZ"),
    DENMARK("Denmark", "Dánia", "DK"),
    DJIBOUTI("Djibouti", "Dzsibuti", "DJ"),
    DOMINICA("Dominica", "Dominika", "DM"),
    DOMINICAN_REPUBLIC("Dominican Republic", "Dominikai Köztársaság", "DO"),
    ECUADOR("Ecuador", "Ecuador", "EC"),
    EGYPT("Egypt", "Egyiptom", "EG"),
    EL_SALVADOR("El Salvador", "Salvador", "SV"),
    EQUATORIAL_GUINEA("Equatorial Guinea", "Egyenlítői-Guinea", "GQ"),
    ERITREA("Eritrea", "Eritrea", "ER"),
    ESTONIA("Estonia", "Észtország", "EE"),
    ESWATINI("Eswatini", "Eswatini", "SZ"),
    ETHIOPIA("Ethiopia", "Etiópia", "ET"),
    FIJI("Fiji", "Fidzsi", "FJ"),
    FINLAND("Finland", "Finnország", "FI"),
    FRANCE("France", "Franciaország", "FR"),
    GABON("Gabon", "Gabon", "GA"),
    GAMBIA("Gambia", "Gambia", "GM"),
    GEORGIA("Georgia", "Grúzia", "GE"),
    GERMANY("Germany", "Németország", "DE"),
    GHANA("Ghana", "Ghána", "GH"),
    GREECE("Greece", "Görögország", "GR"),
    GRENADA("Grenada", "Grenada", "GD"),
    GUATEMALA("Guatemala", "Guatemala", "GT"),
    GUINEA("Guinea", "Guinea", "GN"),
    GUINEA_BISSAU("Guinea-Bissau", "Bissau-Guinea", "GW"),
    GUYANA("Guyana", "Guyana", "GY"),
    HAITI("Haiti", "Haiti", "HT"),
    HONDURAS("Honduras", "Honduras", "HN"),
    HUNGARY("Hungary", "Magyarország", "HU"),
    ICELAND("Iceland", "Izland", "IS"),
    INDIA("India", "India", "IN"),
    INDONESIA("Indonesia", "Indonézia", "ID"),
    IRAN("Iran", "Irán", "IR"),
    IRAQ("Iraq", "Irak", "IQ"),
    IRELAND("Ireland", "Írország", "IE"),
    ISRAEL("Israel", "Izrael", "IL"),
    ITALY("Italy", "Olaszország", "IT"),
    JAMAICA("Jamaica", "Jamaika", "JM"),
    JAPAN("Japan", "Japán", "JP"),
    JORDAN("Jordan", "Jordánia", "JO"),
    KAZAKHSTAN("Kazakhstan", "Kazahsztán", "KZ"),
    KENYA("Kenya", "Kenya", "KE"),
    KIRIBATI("Kiribati", "Kiribati", "KI"),
    KOREA_NORTH("Korea, North", "Észak-Korea", "KP"),
    KOREA_SOUTH("Korea, South", "Dél-Korea", "KR"),
    KOSOVO("Kosovo", "Koszovó", "XK"),
    KUWAIT("Kuwait", "Kuvait", "KW"),
    KYRGYZSTAN("Kyrgyzstan", "Kirgizisztán", "KG"),
    LAOS("Laos", "Laos", "LA"),
    LATVIA("Latvia", "Lettország", "LV"),
    LEBANON("Lebanon", "Libanon", "LB"),
    LESOTHO("Lesotho", "Lesotho", "LS"),
    LIBERIA("Liberia", "Liberia", "LR"),
    LIBYA("Libya", "Líbia", "LY"),
    LIECHTENSTEIN("Liechtenstein", "Liechtenstein", "LI"),
    LITHUANIA("Lithuania", "Litvánia", "LT"),
    LUXEMBOURG("Luxembourg", "Luxemburg", "LU"),
    MADAGASCAR("Madagascar", "Madagaszkár", "MG"),
    MALAWI("Malawi", "Malawi", "MW"),
    MALAYSIA("Malaysia", "Malajzia", "MY"),
    MALDIVES("Maldives", "Maldív-szigetek", "MV"),
    MALI("Mali", "Mali", "ML"),
    MALTA("Malta", "Málta", "MT"),
    MARSHALL_ISLANDS("Marshall Islands", "Marshall-szigetek", "MH"),
    MAURITANIA("Mauritania", "Mauritánia", "MR"),
    MAURITIUS("Mauritius", "Maurícius", "MU"),
    MEXICO("Mexico", "Mexikó", "MX"),
    MICRONESIA("Micronesia", "Mikronézia", "FM"),
    MOLDOVA("Moldova", "Moldova", "MD"),
    MONACO("Monaco", "Monaco", "MC"),
    MONGOLIA("Mongolia", "Mongólia", "MN"),
    MONTENEGRO("Montenegro", "Montenegró", "ME"),
    MOROCCO("Morocco", "Marokkó", "MA"),
    MOZAMBIQUE("Mozambique", "Mozambik", "MZ"),
    MYANMAR("Myanmar", "Mianmar", "MM"),
    NAMIBIA("Namibia", "Namíbia", "NA"),
    NAURU("Nauru", "Nauru", "NR"),
    NEPAL("Nepal", "Nepál", "NP"),
    NETHERLANDS("Netherlands", "Hollandia", "NL"),
    NEW_ZEALAND("New Zealand", "Új-Zéland", "NZ"),
    NICARAGUA("Nicaragua", "Nicaragua", "NI"),
    NIGER("Niger", "Niger", "NE"),
    NIGERIA("Nigeria", "Nigéria", "NG"),
    NORTH_MACEDONIA("North Macedonia", "Észak-Macedónia", "MK"),
    NORWAY("Norway", "Norvégia", "NO"),
    OMAN("Oman", "Omán", "OM"),
    PAKISTAN("Pakistan", "Pakisztán", "PK"),
    PALAU("Palau", "Palau", "PW"),
    PALESTINE("Palestine", "Palesztina", "PS"),
    PANAMA("Panama", "Panama", "PA"),
    PAPUA_NEW_GUINEA("Papua New Guinea", "Pápua Új-Guinea", "PG"),
    PARAGUAY("Paraguay", "Paraguay", "PY"),
    PERU("Peru", "Peru", "PE"),
    PHILIPPINES("Philippines", "Fülöp-szigetek", "PH"),
    POLAND("Poland", "Lengyelország", "PL"),
    PORTUGAL("Portugal", "Portugália", "PT"),
    QATAR("Qatar", "Katar", "QA"),
    ROMANIA("Romania", "Románia", "RO"),
    RUSSIA("Russia", "Oroszország", "RU"),
    RWANDA("Rwanda", "Ruanda", "RW"),
    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis", "Saint Kitts és Nevis", "KN"),
    SAINT_LUCIA("Saint Lucia", "Saint Lucia", "LC"),
    SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines", "Saint Vincent és a Grenadine-szigetek", "VC"),
    SAMOA("Samoa", "Szamoa", "WS"),
    SAN_MARINO("San Marino", "San Marino", "SM"),
    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe", "São Tomé és Príncipe", "ST"),
    SAUDI_ARABIA("Saudi Arabia", "Szaúd-Arábia", "SA"),
    SENEGAL("Senegal", "Szenegál", "SN"),
    SERBIA("Serbia", "Szerbia", "RS"),
    SEYCHELLES("Seychelles", "Seychelle-szigetek", "SC"),
    SIERRA_LEONE("Sierra Leone", "Sierra Leone", "SL"),
    SINGAPORE("Singapore", "Szingapúr", "SG"),
    SLOVAKIA("Slovakia", "Szlovákia", "SK"),
    SLOVENIA("Slovenia", "Szlovénia", "SI"),
    SOLOMON_ISLANDS("Solomon Islands", "Salamon-szigetek", "SB"),
    SOMALIA("Somalia", "Szomália", "SO"),
    SOUTH_AFRICA("South Africa", "Dél-Afrika", "ZA"),
    SOUTH_SUDAN("South Sudan", "Dél-Szudán", "SS"),
    SPAIN("Spain", "Spanyolország", "ES"),
    SRI_LANKA("Sri Lanka", "Srí Lanka", "LK"),
    SUDAN("Sudan", "Szudán", "SD"),
    SURINAME("Suriname", "Suriname", "SR"),
    SWEDEN("Sweden", "Svédország", "SE"),
    SWITZERLAND("Switzerland", "Svájc", "CH"),
    SYRIA("Syria", "Szíria", "SY"),
    TAJIKISTAN("Tajikistan", "Tádzsikisztán", "TJ"),
    TANZANIA("Tanzania", "Tanzánia", "TZ"),
    THAILAND("Thailand", "Thaiföld", "TH"),
    TIMOR_LESTE("Timor-Leste", "Kelet-Timor", "TL"),
    TOGO("Togo", "Togo", "TG"),
    TONGA("Tonga", "Tonga", "TO"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago", "Trinidad és Tobago", "TT"),
    TUNISIA("Tunisia", "Tunézia", "TN"),
    TURKEY("Turkey", "Törökország", "TR"),
    TURKMENISTAN("Turkmenistan", "Türkmenisztán", "TM"),
    TUVALU("Tuvalu", "Tuvalu", "TV"),
    UGANDA("Uganda", "Uganda", "UG"),
    UKRAINE("Ukraine", "Ukrajna", "UA"),
    UNITED_ARAB_EMIRATES("United Arab Emirates", "Egyesült Arab Emírségek", "AE"),
    UNITED_KINGDOM("United Kingdom", "Egyesült Királyság", "GB"),
    UNITED_STATES("United States", "Egyesült Államok", "US"),
    URUGUAY("Uruguay", "Uruguay", "UY"),
    UZBEKISTAN("Uzbekistan", "Üzbegisztán", "UZ"),
    VANUATU("Vanuatu", "Vanuatu", "VU"),
    VATICAN_CITY("Vatican City", "Vatikán", "VA"),
    VENEZUELA("Venezuela", "Venezuela", "VE"),
    VIETNAM("Vietnam", "Vietnám", "VN"),
    YEMEN("Yemen", "Jemen", "YE"),
    ZAMBIA("Zambia", "Zambia", "ZM"),
    ZIMBABWE("Zimbabwe", "Zimbabwe", "ZW");

    private final String englishName;
    private final String hungarianName;
    private final String countryCode;
}
